### ISSUE TITLE
ped not showing

### ISSUE THREAD

**Issue by NotPhelps** [Mustachedom/md-fishing#3]
so some of my community can not see the ped unless i restart the script while thye are in game ive had themfix texture budget and ive had them even clear cache nothing had worked any ideas on this ?

**Comment by Mustachedom** [comment]
tell them to check their f8 console, they may not be loading the model fast enough the first time especially if its only a few people

**Comment by HavekHD** [comment]
Are you using qb, esx, ox, qbox?

**Comment by NotPhelps** [comment]
> tell them to check their f8 console, they may not be loading the model fast enough the first time especially if its only a few people

so i did some testing and found the issue to be lib.requestModel("u_m_m_blane", 15000) and i just made the 15000 25000 and now everyone can see it fine and all working again it seems i was the only one that could see it idk enough about oxlib or lib.requestModel to know why the number must be higher for some then other idk lol

**Comment by NotPhelps** [comment]
> Are you using qb, esx, ox, qbox?

qb

**Comment by Mustachedom** [comment]
thats crazy haha so lib.requestModel does 500 unless specified 

so lib.requestModel('u_m_m_blane') would be the same as  lib.requestModel('u_m_m_blane', 500)  

so i set it to 15000 so people wouldnt have this issue but i guess if their connection is slow enough it could take that long in theory

**Comment by NotPhelps** [comment]
> thats crazy haha so lib.requestModel does 500 unless specified
> 
> so lib.requestModel('u_m_m_blane') would be the same as lib.requestModel('u_m_m_blane', 500)
> 
> so i set it to 15000 so people wouldnt have this issue but i guess if their connection is slow enough it could take that long in theory

yeah a friend of mine gave the idea to go higher then what was there so i did and at server restart had everyone test and see they could and yeah the peds are there and working perfectly lol
